/** @type { import('@storybook/react').Preview } */
import React from "react";
import { TractorbeamProvider } from "../src/components/tractorbeam-provider";
import { Preview } from "@storybook/react";
import { TractorbeamAI } from "@tractorbeamai/backend";

const preview: Preview = {
    loaders: [
        async () => {
            const tb = new TractorbeamAI(
                "pk_LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvVGhnWmhpRVRMSG9KTlVLNFpKeQpnYUZJbnNueFlvWCtiTUZFN3pIQzdPQkxuNElreUdvY0ZOM2pWMEFzYnJIOGQ0UEpFaUFCeEdlYTJMWXphL2VtCk1qejBKRkFhTWxKRlhqbGs5emNSLy80WmJDcDV5dkJFcHdZOHRDN1JGa2VPUkh5MEEyQ0V4T1ZVd2kzdEhBQ2cKcy9uRTM1OGdkZUcxOGhNd2F4VzFsbTU1cEF6bWVSWDd2anh6Zm1jbGl1Z3VYZk96NlZtcFcwL1ZPSFB3SFZUTApGSTl1OGIzMXlZVHMzOUhmS1ZuNmFQZ1BYMitndlhhaDJGSE9GZHlWMWJsanp0UzIzcUFNRzI1ZmdjaFhkRUFFCnlBNlJDODJRWW9lUkdSS05YT21sWkl6bEZuN0xCNjd0MDA4SGpXWlJER3lkTmxDWTI1TFZTd1JqYTVJeDhIbXEKZndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==",
                "sk_LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2hPR0JtR0lSTXNlZ2sKMVFyaGtuS0JvVWlleWZGaWhmNXN3VVR2TWNMczRFdWZnaVRJYWh3VTNlTlhRQ3h1c2Z4M2c4a1NJQUhFWjVyWQp0ak5yOTZZeVBQUWtVQm95VWtWZU9XVDNOeEgvL2hsc0tubks4RVNuQmp5MEx0RVdSNDVFZkxRRFlJVEU1VlRDCkxlMGNBS0N6K2NUZm55QjE0Ylh5RXpCckZiV1dibm1rRE9aNUZmdStQSE4rWnlXSzZDNWQ4N1BwV2FsYlQ5VTQKYy9BZFZNc1VqMjd4dmZYSmhPemYwZDhwV2ZwbytBOWZiNkM5ZHFIWVVjNFYzSlhWdVdQTzFMYmVvQXdiYmwrQgp5RmQwUUFUSURwRUx6WkJpaDVFWkVvMWM2YVZrak9VV2Zzc0hydTNUVHdlTlpsRU1iSjAyVUpqYmt0VkxCR05yCmtqSHdlYXAvQWdNQkFBRUNnZ0VBVHFncFRCYUJFY1FvM1ROOTVCRWx3YjRWSnJlakIrMFU5UzJVT3RrOTM0RU4KRkUwVU1oMm5CcjA5S2pmNmxhVkw1bW1MSThjdTVZcWd2ME9oc2ZiNUJJQzlvcXZjSkJvRWt4U1FnSmJETnZEYgpxV3pOMENmS2J1ejVsL1ZSZUx1L213VjJkRUZXZFpQbjl2Y2VQRy9IK0JjUHFRVERldy84eTViMkpBRExBQkd1CmhtOUFrZTVjd0FUbHgwU3BxUngvVjl6dFI4OVJ1SlRGRGdJWGlVem1ENnhDemFCR2pBb0U3bFhMZC9uY1NMcXEKb1VIMU5ldjA1b21LSXN3Z1JpVjhxY2tVbU1Hc2tHQWwyVFdpYnIzZWV6dXFNQVVlWWRzSmNSbzBrZ0dybHV1WQpVYnpGbFRUeU5rUmNQWDNOM054b0VBVDB6YzFkdHg3TWZTTTJRSk9JZ1FLQmdRRGJBbWk2TXE3UW9TRVhLYUV0Cnh5dTAwY2VGdktEVHhhUmFqZXYwUGt6UUNLNXNyZjk0RlVTWGdWNlhNM0hSUmtwcjVXUlVTbng1LzFidkdpaWkKcGpCSzBheHZwQkRidGlzUjVqNUFmS1A2MUZ1ZTVlNk02emRrWkQvRjd0YzlXNDRtVk05ckxSbUJSemVYQjdNdgpHWG55Z25yUXg5ZEMrSkluTmZOSXZ4UFZnUUtCZ1FDOGMwTWFndXB2Z1ZGTEUzbEhmM2o2TlFwK0RHZEkrejBsCmFuMncrZlVIMlJpTW5xbjNIVVU4MUo5bjVGQnhFM2w4ZEVsdXNZRnk2bHF5c0hEY0l4dUlKYlVyNUd1bmQwNisKRXdmZ2R2d1B4WksxZGt2NkpwNFdHbXhTOFlYUlRXTmNBZG41UzltRzVQOXh3YVdyeWg4STV2S2FHQ2lyblVRSApqVkFpRFUxLy93S0JnQlJ4NXlEcXRsTVhsNlUzNTZvRVc5b25jejdTMnhpcDdLdmZiOVYvTTJDQVR2Z3FUaDBCCnIwT05laTBYU2xyRSt4R1Rlb2c3NDk3bnJVL28yejVEMFdKS3JKUkhkcU5zSUIwdHAwWVIzS1QveWdYTlpUV1cKaDdkQmZJcVh2MVFsQmVJaUxMTE9wUURpaXhmNFNndnRqdXJLcjNocUQzaGJDQm5NK1ljaS8xRUJBb0dBUUFJVwpaTWJhd2d6Mmc3MlZrQWRvRy9Rd0lDZ3VYTWVaT1VBMmVRb3RoQURsS2I0cWxOaklUNlVZajcwbzVYOXI0QzNQClUxM1BUaXp6cVlYc2o1a05ITzFSNEJxeHhpdnIvdnVQelZvY3UyNnNLaDZJSitzOS90dnl0eWw1L21GK3doMk8KMy9JM2JHNFRwWnZVbmNrRlNZeklFamJxZVgvdFAzTnNLR1RFVWhrQ2dZQUVsVDgwQXdWaTNGQTFPV1IyZVJVZAphblJQd3pjV0V5SkdzMWNNd3NMZVZkZXZ6bHVqQVZEM08yejZLaDRFVDgwVG1QenFJUk9SVFZ4MXR4NktjQkZsCmJ1TEVRWjE5ODZRRDlYbHNXNmdyem1oQ2VLTmNHS05MVmZxeGxnMG5mTHU4TXZKTUw2YXlqS2txVkhSMjRXb00KcjEwQk9oc1hhUTNrQjY0SGhoRE4xUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K",
            );

            const token = await tb.createToken({
                identity: "wbfletch@gmail.com",
                projectId: 1,
            });

            return { token };
        },
    ],
    decorators: [
        (Story, { loaded: { token } }) => (
            <TractorbeamProvider
                token={token}
                apiURL="https://463a-205-178-113-127.ngrok-free.app"
            >
                <Story />
            </TractorbeamProvider>
        ),
    ],
};

export default preview;
